### ISSUE TITLE
Develop GTFS Realtime feed page

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-feed-api#353]
## Tasks

- [ ] [Match GTFS Realtime individual feed page](https://www.figma.com/file/LZVQecGplb4Lnuh7a24Jef/GTFS-Tool-Forms?type=design&node-id=1254%3A1743&mode=design&t=ztQe5LNqVxOuqd8y-1). Using v1/gtfs_rt_feeds/id
- [ ]  Entity type should be transformed to: 

          sa = Service Alerts
          tu = Trip Updates
          vp = Vehicle Positions

- [ ] "Auth Parameter" should have a different prefix based on the authentication type: 

            1 = API Key
            2 = HTTP

## Context
- Open the Data Sync plugin in Figma to see related fields in the API
<img width="303" alt="Screenshot 2024-04-05 at 10 47 14 AM" src="https://github.com/MobilityData/mobility-feed-api/assets/90632321/1971b961-9c5a-4f18-b568-93e9787e9f8f">

- All null values should not be displayed.
